// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: api/blog/v1/blog.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Like          int64                  `protobuf:"varint,4,opt,name=like,proto3" json:"like,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_api_blog_v1_blog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_api_blog_v1_blog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_api_blog_v1_blog_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetLike() int64 {
	if x != nil {
		return x.Like
	}
	return 0
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"` // the title of string must be between 5 and 50 character
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_api_blog_v1_blog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_blog_v1_blog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_blog_v1_blog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=Article,proto3" json:"Article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleReply) Reset() {
	*x = CreateArticleReply{}
	mi := &file_api_blog_v1_blog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleReply) ProtoMessage() {}

func (x *CreateArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_blog_v1_blog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleReply.ProtoReflect.Descriptor instead.
func (*CreateArticleReply) Descriptor() ([]byte, []int) {
	return file_api_blog_v1_blog_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticleReply) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type UpdateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"` // the title of string must be between 5 and 50 character;
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_api_blog_v1_blog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_blog_v1_blog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_blog_v1_blog_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=Article,proto3" json:"Article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleReply) Reset() {
	*x = UpdateArticleReply{}
	mi := &file_api_blog_v1_blog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleReply) ProtoMessage() {}

func (x *UpdateArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_blog_v1_blog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleReply.ProtoReflect.Descriptor instead.
func (*UpdateArticleReply) Descriptor() ([]byte, []int) {
	return file_api_blog_v1_blog_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateArticleReply) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_api_blog_v1_blog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_blog_v1_blog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_blog_v1_blog_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleReply) Reset() {
	*x = DeleteArticleReply{}
	mi := &file_api_blog_v1_blog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleReply) ProtoMessage() {}

func (x *DeleteArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_blog_v1_blog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleReply.ProtoReflect.Descriptor instead.
func (*DeleteArticleReply) Descriptor() ([]byte, []int) {
	return file_api_blog_v1_blog_proto_rawDescGZIP(), []int{6}
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_api_blog_v1_blog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_blog_v1_blog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_blog_v1_blog_proto_rawDescGZIP(), []int{7}
}

func (x *GetArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=Article,proto3" json:"Article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleReply) Reset() {
	*x = GetArticleReply{}
	mi := &file_api_blog_v1_blog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleReply) ProtoMessage() {}

func (x *GetArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_blog_v1_blog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleReply.ProtoReflect.Descriptor instead.
func (*GetArticleReply) Descriptor() ([]byte, []int) {
	return file_api_blog_v1_blog_proto_rawDescGZIP(), []int{8}
}

func (x *GetArticleReply) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type ListArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleRequest) Reset() {
	*x = ListArticleRequest{}
	mi := &file_api_blog_v1_blog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleRequest) ProtoMessage() {}

func (x *ListArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_blog_v1_blog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleRequest.ProtoReflect.Descriptor instead.
func (*ListArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_blog_v1_blog_proto_rawDescGZIP(), []int{9}
}

type ListArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Article             `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleReply) Reset() {
	*x = ListArticleReply{}
	mi := &file_api_blog_v1_blog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleReply) ProtoMessage() {}

func (x *ListArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_blog_v1_blog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleReply.ProtoReflect.Descriptor instead.
func (*ListArticleReply) Descriptor() ([]byte, []int) {
	return file_api_blog_v1_blog_proto_rawDescGZIP(), []int{10}
}

func (x *ListArticleReply) GetResults() []*Article {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_api_blog_v1_blog_proto protoreflect.FileDescriptor

const file_api_blog_v1_blog_proto_rawDesc = "" +
	"\n" +
	"\x16api/blog/v1/blog.proto\x12\ablog.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"]\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04like\x18\x04 \x01(\x03R\x04like\"Q\n" +
	"\x14CreateArticleRequest\x12\x1f\n" +
	"\x05title\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x05\x182R\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"@\n" +
	"\x12CreateArticleReply\x12*\n" +
	"\aArticle\x18\x01 \x01(\v2\x10.blog.v1.ArticleR\aArticle\"j\n" +
	"\x14UpdateArticleRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12\x1f\n" +
	"\x05title\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x05\x182R\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"@\n" +
	"\x12UpdateArticleReply\x12*\n" +
	"\aArticle\x18\x01 \x01(\v2\x10.blog.v1.ArticleR\aArticle\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteArticleReply\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"=\n" +
	"\x0fGetArticleReply\x12*\n" +
	"\aArticle\x18\x01 \x01(\v2\x10.blog.v1.ArticleR\aArticle\"\x14\n" +
	"\x12ListArticleRequest\">\n" +
	"\x10ListArticleReply\x12*\n" +
	"\aresults\x18\x01 \x03(\v2\x10.blog.v1.ArticleR\aresults2\xfd\x03\n" +
	"\vBlogService\x12c\n" +
	"\rCreateArticle\x12\x1d.blog.v1.CreateArticleRequest\x1a\x1b.blog.v1.CreateArticleReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/article\x12h\n" +
	"\rUpdateArticle\x12\x1d.blog.v1.UpdateArticleRequest\x1a\x1b.blog.v1.UpdateArticleReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/article/{id}\x12e\n" +
	"\rDeleteArticle\x12\x1d.blog.v1.DeleteArticleRequest\x1a\x1b.blog.v1.DeleteArticleReply\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/article/{id}\x12\\\n" +
	"\n" +
	"GetArticle\x12\x1a.blog.v1.GetArticleRequest\x1a\x18.blog.v1.GetArticleReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/article/{id}\x12Z\n" +
	"\vListArticle\x12\x1b.blog.v1.ListArticleRequest\x1a\x19.blog.v1.ListArticleReply\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/articleB\x17Z\x15agdemo/api/blog/v1;v1b\x06proto3"

var (
	file_api_blog_v1_blog_proto_rawDescOnce sync.Once
	file_api_blog_v1_blog_proto_rawDescData []byte
)

func file_api_blog_v1_blog_proto_rawDescGZIP() []byte {
	file_api_blog_v1_blog_proto_rawDescOnce.Do(func() {
		file_api_blog_v1_blog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_blog_v1_blog_proto_rawDesc), len(file_api_blog_v1_blog_proto_rawDesc)))
	})
	return file_api_blog_v1_blog_proto_rawDescData
}

var file_api_blog_v1_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_blog_v1_blog_proto_goTypes = []any{
	(*Article)(nil),              // 0: blog.v1.Article
	(*CreateArticleRequest)(nil), // 1: blog.v1.CreateArticleRequest
	(*CreateArticleReply)(nil),   // 2: blog.v1.CreateArticleReply
	(*UpdateArticleRequest)(nil), // 3: blog.v1.UpdateArticleRequest
	(*UpdateArticleReply)(nil),   // 4: blog.v1.UpdateArticleReply
	(*DeleteArticleRequest)(nil), // 5: blog.v1.DeleteArticleRequest
	(*DeleteArticleReply)(nil),   // 6: blog.v1.DeleteArticleReply
	(*GetArticleRequest)(nil),    // 7: blog.v1.GetArticleRequest
	(*GetArticleReply)(nil),      // 8: blog.v1.GetArticleReply
	(*ListArticleRequest)(nil),   // 9: blog.v1.ListArticleRequest
	(*ListArticleReply)(nil),     // 10: blog.v1.ListArticleReply
}
var file_api_blog_v1_blog_proto_depIdxs = []int32{
	0,  // 0: blog.v1.CreateArticleReply.Article:type_name -> blog.v1.Article
	0,  // 1: blog.v1.UpdateArticleReply.Article:type_name -> blog.v1.Article
	0,  // 2: blog.v1.GetArticleReply.Article:type_name -> blog.v1.Article
	0,  // 3: blog.v1.ListArticleReply.results:type_name -> blog.v1.Article
	1,  // 4: blog.v1.BlogService.CreateArticle:input_type -> blog.v1.CreateArticleRequest
	3,  // 5: blog.v1.BlogService.UpdateArticle:input_type -> blog.v1.UpdateArticleRequest
	5,  // 6: blog.v1.BlogService.DeleteArticle:input_type -> blog.v1.DeleteArticleRequest
	7,  // 7: blog.v1.BlogService.GetArticle:input_type -> blog.v1.GetArticleRequest
	9,  // 8: blog.v1.BlogService.ListArticle:input_type -> blog.v1.ListArticleRequest
	2,  // 9: blog.v1.BlogService.CreateArticle:output_type -> blog.v1.CreateArticleReply
	4,  // 10: blog.v1.BlogService.UpdateArticle:output_type -> blog.v1.UpdateArticleReply
	6,  // 11: blog.v1.BlogService.DeleteArticle:output_type -> blog.v1.DeleteArticleReply
	8,  // 12: blog.v1.BlogService.GetArticle:output_type -> blog.v1.GetArticleReply
	10, // 13: blog.v1.BlogService.ListArticle:output_type -> blog.v1.ListArticleReply
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_blog_v1_blog_proto_init() }
func file_api_blog_v1_blog_proto_init() {
	if File_api_blog_v1_blog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_blog_v1_blog_proto_rawDesc), len(file_api_blog_v1_blog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_blog_v1_blog_proto_goTypes,
		DependencyIndexes: file_api_blog_v1_blog_proto_depIdxs,
		MessageInfos:      file_api_blog_v1_blog_proto_msgTypes,
	}.Build()
	File_api_blog_v1_blog_proto = out.File
	file_api_blog_v1_blog_proto_goTypes = nil
	file_api_blog_v1_blog_proto_depIdxs = nil
}
